import { NextFont } from "next/dist/compiled/@next/font";
import Provider from "./Provider";
import "./globals.css";
import { Raleway } from "next/font/google";

const raleway: NextFont = Raleway({ subsets: ["latin"] });

export const metadata: {
  title: string;
  description: string;
} = {
  title: "Prime",
  description: "Generated by Prime",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): any {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
